# -*- coding: utf-8 -*-
"""Face_detaction_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHIpIXSZfCBTz4XQXGmhMUoiVqTBssJL
"""

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.models import load_model
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
from tensorflow.keras import applications

# path to your model file in Drive
MODEL_PATH = '/content/drive/MyDrive/Skin_Problem_Model/best_head_only.keras'  # or .h5

# Load the model
model = load_model(MODEL_PATH)
print("✅ Model loaded successfully!")

# Define the class names that your model was trained on.
CLASS_NAMES = ['Acne', 'Blackheads', 'Dark Spots', 'Dry Skin', 'Eye bags', 'Normal Skin', 'Oily Skin', 'Pores', 'Skin Redness', 'Wrinkles']



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from PIL import Image
# import numpy as np
# import io
# import os
# from pathlib import Path
# import base64
# import tempfile
# import textwrap
# 
# # TensorFlow/Keras imports (import lazily to avoid heavy startup in dev)
# try:
#     # Import tensorflow only when needed
#     import tensorflow as tf
#     from tensorflow.keras.models import load_model
#     from tensorflow.keras.preprocessing import image as keras_image
#     from tensorflow.keras.applications import mobilenet
#     TF_AVAILABLE = True
# except Exception as e:
#     TF_AVAILABLE = False
# 
# st.set_page_config(
#     page_title="AI Skin Classifier",
#     page_icon="👩‍⚕️",
#     layout="wide"
# )
# 
# # ---------------------
# # Helper utilities
# # ---------------------
# @st.cache_resource
# def load_keras_model(paths_to_try=None):
#     """
#     Try a list of paths for the Keras model. Return the loaded model or None.
#     This function is cached so the model is loaded only once per session.
#     """
#     if not TF_AVAILABLE:
#         return None, "tensorflow_import_error"
# 
#     if paths_to_try is None:
#         paths_to_try = [
#             "./model/best_head_only.keras",
#             "./model/best_head_only.h5",
#             "/content/drive/MyDrive/Skin_Problem_Model/best_head_only.keras",
#             "/content/drive/MyDrive/Skin_Problem_Model/best_head_only.h5",
#         ]
# 
#     last_err = None
#     for p in paths_to_try:
#         try:
#             p = str(p)
#             if os.path.exists(p):
#                 model = load_model(p)
#                 return model, p
#         except Exception as e:
#             last_err = e
#     return None, last_err
# 
# def preprocess_pil(img_pil, target_size=(224,224)):
#     img = img_pil.convert("RGB").resize(target_size)
#     x = keras_image.img_to_array(img)
#     x = np.expand_dims(x, axis=0)
#     x = mobilenet.preprocess_input(x)
#     return x
# 
# def get_logo_bytes(logo_path:Path):
#     if logo_path.exists():
#         return logo_path.read_bytes()
#     return None
# 
# def show_image_with_border(img, caption=None, width=None):
#     st.image(img, caption=caption, use_column_width=(width is None))
# 
# def format_confidence_to_percent(val):
#     return float(val*100)
# 
# # ---------------------
# # UI / Layout
# # ---------------------
# st.markdown(
#     """
#     <style>
#     .main { background: linear-gradient(135deg, #f7f9ff 0%, #fef6fb 100%); }
#     .stApp { background: linear-gradient(135deg, #f7f9ff 0%, #fef6fb 100%); }
#     .prediction-box { border-radius: 12px; padding: 14px; background: rgba(255,255,255,0.95); box-shadow: 0 6px 18px rgba(0,0,0,0.06); }
#     </style>
#     """,
#     unsafe_allow_html=True
# )
# 
# # Optional local logo — place a file at assets/logo.png if you want a custom logo
# ASSETS_DIR = Path("assets")
# ASSETS_DIR.mkdir(exist_ok=True)
# logo_path = ASSETS_DIR / "logo.png"
# logo_bytes = get_logo_bytes(logo_path)
# c1, c2 = st.columns([1, 5])
# with c1:
#     if logo_bytes:
#         st.image(logo_bytes, width=110)
#     else:
#         st.markdown("### 👩‍⚕️\n**Skin Classifier**")
# with c2:
#     st.markdown("## AI-Based Skin Problem Classifier")
#     st.markdown(
#         "Upload a clear facial/skin photo and the model will predict the most likely skin conditions. "
#         "This app shows top predictions and confidence. ⚠️ Not a medical diagnosis — consult a dermatologist."
#     )
# 
# st.write("---")
# 
# # ---------------------
# # Config / Class names
# # ---------------------
# DEFAULT_CLASS_NAMES = [
#     'Acne', 'Blackheads', 'Dark Spots', 'Dry Skin', 'Eye bags',
#     'Normal Skin', 'Oily Skin', 'Pores', 'Skin Redness', 'Wrinkles'
# ]
# 
# # Allow user to override class names quickly (advanced)
# CLASS_NAMES = DEFAULT_CLASS_NAMES
# 
# # ---------------------
# # Model loading
# # ---------------------
# st.sidebar.header("Model options")
# st.sidebar.markdown("Choose how to load the model:")
# 
# load_mode = st.sidebar.radio("Load mode", ("Auto (try default paths)", "Upload model file (.keras/.h5)"))
# 
# model = None
# model_path_used = None
# 
# if load_mode == "Auto (try default paths)":
#     with st.sidebar.expander("Paths tried (editable)"):
#         default_paths = "\n".join([
#             "./model/best_head_only.keras",
#             "./model/best_head_only.h5",
#             "/content/drive/MyDrive/Skin_Problem_Model/best_head_only.keras",
#             "/content/drive/MyDrive/Skin_Problem_Model/best_head_only.h5"
#         ])
#         user_paths = st.text_area("One path per line:", value=default_paths, height=120)
#     paths_list = [p.strip() for p in user_paths.splitlines() if p.strip()]
#     with st.spinner("Loading model (auto)..."):
#         model, model_path_used = load_keras_model(paths_list)
#         if model is None:
#             if model_path_used == "tensorflow_import_error":
#                 st.sidebar.error("TensorFlow import failed. Make sure tensorflow is installed.")
#             else:
#                 st.sidebar.warning("Model not found in paths. You can switch to 'Upload model file' to upload a model.")
#         else:
#             st.sidebar.success(f"Model loaded from: {model_path_used}")
# 
# else:
#     uploaded_model_file = st.sidebar.file_uploader("Upload a Keras model (.keras or .h5)", type=["keras", "h5"])
#     if uploaded_model_file is not None:
#         # save to a temporary location and load
#         tmp_dir = Path("model")
#         tmp_dir.mkdir(exist_ok=True)
#         tmp_path = tmp_dir / uploaded_model_file.name
#         with open(tmp_path, "wb") as f:
#             f.write(uploaded_model_file.getbuffer())
#         with st.spinner("Loading uploaded model..."):
#             try:
#                 model = load_model(str(tmp_path))
#                 model_path_used = str(tmp_path)
#                 st.sidebar.success(f"Model loaded from uploaded file: {tmp_path.name}")
#             except Exception as e:
#                 st.sidebar.error(f"Failed to load uploaded model: {e}")
# 
# 
# # If model not loaded, show instructions and fallback
# if model is None:
#     st.warning("Model is not loaded. To use the app you must either place the model in `./model/` or upload it via the sidebar.")
#     st.info(
#         "If you have the model in Google Drive (Colab), either download it locally to the repo `model/` folder or upload it here."
#     )
# 
# # ---------------------
# # Main app area
# # ---------------------
# col_img, col_ctrl = st.columns([1.2, 1])
# 
# with col_img:
#     st.markdown("### 📸 Upload or try sample images")
#     uploaded_file = st.file_uploader("Upload an image (jpg/png)", type=["jpg", "jpeg", "png"])
#     st.markdown("OR")
#     st.markdown("Select a sample image (if included in `assets/samples/`)")
#     samples_dir = ASSETS_DIR / "samples"
#     if samples_dir.exists():
#         sample_files = sorted(list(samples_dir.glob("*.*")))
#     else:
#         sample_files = []
#     sample_choice = None
#     if len(sample_files) > 0:
#         sample_names = [p.name for p in sample_files]
#         sample_choice = st.selectbox("Choose sample", ["-- none --"] + sample_names)
#     else:
#         st.info("No sample images found. Put sample images in `assets/samples/` if you want quick tests.")
# 
#     # Decide which image to use
#     pil_img = None
#     if uploaded_file is not None:
#         try:
#             pil_img = Image.open(uploaded_file)
#         except Exception as e:
#             st.error(f"Cannot open uploaded file: {e}")
#     elif sample_choice and sample_choice != "-- none --":
#         pil_img = Image.open(samples_dir / sample_choice)
# 
#     if pil_img is not None:
#         show_image_with_border(pil_img, caption="Input image (resized for model preview)")
#     else:
#         st.markdown("No image loaded yet. Upload or select a sample to run prediction.")
# 
# with col_ctrl:
#     st.markdown("### 🔧 Prediction settings")
#     top_k = st.slider("How many top predictions to show", min_value=1, max_value=5, value=3)
#     run_button = st.button("Run prediction", type="primary")
# 
# # Advanced: allow user to edit class names (careful, should match model output order)
# with st.expander("Advanced: Edit class names (must match model output order)"):
#     text_classes = st.text_area("One class per line (order matters)", value="\n".join(CLASS_NAMES), height=190)
#     try:
#         edited = [s.strip() for s in text_classes.splitlines() if s.strip()]
#         if len(edited) > 0:
#             CLASS_NAMES = edited
#     except Exception:
#         pass
# 
# # Run prediction
# if run_button:
#     if pil_img is None:
#         st.error("Please upload or select an image first.")
#     elif model is None:
#         st.error("Model not loaded. Upload model file in the sidebar or place model in `./model/`.")
#     else:
#         try:
#             with st.spinner("Preprocessing image and predicting..."):
#                 x = preprocess_pil(pil_img, target_size=(224,224))
#                 preds = model.predict(x)[0]
#                 # safety: if softmax output length doesn't match
#                 n_out = len(preds)
#                 if n_out != len(CLASS_NAMES):
#                     st.warning(f"Model output length ({n_out}) != number of class names ({len(CLASS_NAMES)}). Using first {min(n_out, len(CLASS_NAMES))} classes.")
#                 # get top k
#                 top_idx = np.argsort(preds)[-top_k:][::-1]
#                 st.markdown("### 🩺 Prediction Results")
#                 st.markdown("<div class='prediction-box'>", unsafe_allow_html=True)
#                 for idx in top_idx:
#                     cn = CLASS_NAMES[idx] if idx < len(CLASS_NAMES) else f"class_{idx}"
#                     conf = preds[idx]
#                     pct = format_confidence_to_percent(conf)
#                     st.write(f"**{cn}** — {pct:.2f}%")
#                     # progress bars expect 0-100 int
#                     p_int = int(np.clip(pct, 0, 100))
#                     st.progress(p_int)
#                 st.markdown("</div>", unsafe_allow_html=True)
#                 st.info("Tip: This is a trained model output. For medical advice, consult a professional.")
#         except Exception as e:
#             st.error(f"Error during prediction: {e}")
# 
# # Footer / useful links
# st.write("---")
# st.markdown(
#     """
#     **Notes & Troubleshooting**
#     - Place the model file inside `./model/` or upload via the sidebar.
#     - If you used a different preprocessing during training (not Mobilenet preprocessing), update `preprocess_pil`.
#     - Model files can be large — don't upload to GitHub if >100MB (use Git LFS or store model in Drive and load from there).
#     """
# )
# 
# # Small "download example" helper: allow user to download an example README if they want
# if st.button("Show quick README for GitHub (copy)"):
#     quick_readme = textwrap.dedent("""
#     # AI Skin Classifier
# 
#     Files:
#     - app.py       # Streamlit app
#     - requirements.txt
#     - assets/      # logo.png and optional sample images (assets/samples/)
#     - model/       # (not included) put best_head_only.keras or .h5 here
# 
#     Run locally:
#     1. pip install -r requirements.txt
#     2. streamlit run app.py
# 
#     Notes:
#     - Put your trained model in model/ or upload it via the sidebar.
#     - This app uses mobilenet preprocessing by default; ensure training used the same preprocessing.
#     """)
#     st.code(quick_readme)

from pyngrok import ngrok

# Replace "YOUR_NEW_NGROK_AUTHTOKEN" with your actual ngrok authtoken
# You can get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("34EsYn8x7DQ0ccmHZAZgWmzzXEs_6EoWFguDuqCiNFh21PxsW")

!pip install pyngrok

# Run Streamlit and create a public link
get_ipython().system('streamlit run app.py &>/dev/null&')
public_url = ngrok.connect(8501)
print("✅ Your Streamlit app is live at:")
print(public_url)

import subprocess
import os

def find_and_kill_streamlit():
    try:
        # Find the process ID of the streamlit process
        # We look for processes running the 'streamlit' command
        # and exclude the grep process itself
        pgrep_command = "pgrep -f 'streamlit run'"
        process = subprocess.run(pgrep_command, shell=True, capture_output=True, text=True)
        pids = process.stdout.strip().split('\n')

        if not pids or pids == ['']:
            print("No Streamlit process found.")
            return

        print(f"Found Streamlit process(es) with PID(s): {', '.join(pids)}")

        # Kill the processes
        for pid in pids:
            try:
                os.kill(int(pid), 9) # Signal 9 is SIGKILL
                print(f"Killed process {pid}")
            except OSError as e:
                print(f"Error killing process {pid}: {e}")

    except Exception as e:
        print(f"An error occurred: {e}")

# Run the function to find and kill Streamlit
find_and_kill_streamlit()